services:
    app:
        user: 1000:1000
        build: .
        ports:
            - 8000:8000
        volumes:
            - ./app/:/app/
        env_file: 
            ./env/.app.env
        environment:
            - DB_HOST=db
        command: sh -c "python manage.py runserver 0.0.0.0:8000"
        depends_on:
            - db
        links:
            - db:db
    db:
        image: postgres:12-alpine
        env_file: 
            ./env/.db.env
