services:
    app:
        user: user:user
        build: .
        ports:
            - 8000:8000
        volumes:
            - ./app/:/app/
        env_file: 
            ./env/.app.env
        environment:
            - DB_HOST=db
        depends_on:
            - db
        command: >
            sh -c "python manage.py wait_for_db &&
                   python manage.py migrate &&
                   python manage.py runserver 0.0.0.0:8000"

    db:
        image: postgres:12-alpine
        env_file: 
            ./env/.db.env