name: docker-compose-actions-workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Creating enviroment folder
        run: mkdir env
      - name: Creating enviroment db file
        run: |
          echo POSTGRES_DB=${{secrets.POSTGRES_DB}} >> env/.db.env &&
          echo POSTGRES_USER=${{secrets.POSTGRES_USER}} >> env/.db.env &&
          echo POSTGRES_PASSWORD=${{secrets.POSTGRES_PASSWORD}} >> env/.db.env
      - name: Creating enviroment app file
        run: | 
          echo DB_NAME=${{secrets.POSTGRES_DB}} >> env/.app.env &&
          echo DB_USER=${{secrets.POSTGRES_USER}} >> env/.app.env &&
          echo DB_PASS=${{secrets.POSTGRES_PASSWORD}} >> env/.app.env &&
          echo SECRET_KEY=4{{secrets.SECRET_KEY}} >> env/.app.env
      - name: Build
        run: docker-compose build
      - name: Test
        run: |
          docker-compose run --rm app sh -c "python manage.py wait_for_db &&
          python manage.py test &&
          flake8"